apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: ovpdpwy1r-java-springboot-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/ovpdpwy1r-java-springboot-gitops